{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {
    "deletable": true,
    "editable": true
   },
   "source": [
    "## Error Management\n",
    "\n",
    "If memory management in C, can be seen as a powerfull tool, when combined with C error management, it definitely becomes the main reason of buggy C programs. Actually, error management in C is tradionnally based on integer return code which makes it at the same time very poor and very weak:\n",
    "\n",
    "* very poor: because a simple integer does not hold any context, it cannot tell a lot on the reason of an issue;\n",
    "* very weak: because using the result of a function is not mandatory in C, it is very easy to just forget the returned code.\n",
    "\n",
    "For the first problem, `errno`, `perror()` and `strerror()` functions are provided but they are a pain to use, as shown by the code below:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {
    "collapsed": false,
    "deletable": true,
    "editable": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Something wrong happened: No such file or directory\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": []
    }
   ],
   "source": [
    "#include <errno.h>\n",
    "#include <stdlib.h>\n",
    "#include <stdio.h>\n",
    "#include <string.h>\n",
    "\n",
    "int main(void) {\n",
    "    errno = 0;                                                   // (1) Don't forget that!\n",
    "    FILE * file = fopen(\"/a/non/existent/file\", \"r\");\n",
    "    if (NULL == file) {                                          // (2) Don't forget that!\n",
    "        char * msg = strerror(errno);                            // (3) Not thread-safe\n",
    "        fprintf(stderr, \"Something wrong happened: %s\\n\", msg);  // (4) Does the  message holds all required information? \n",
    "        // free(msg);                                            // (5) Don't do that, segfault guaranteed!\n",
    "    } else {\n",
    "        printf(\"Strange: you really have such a file?\\n\");       // This should not happened\n",
    "    }\n",
    "    \n",
    "}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "deletable": true,
    "editable": true
   },
   "source": [
    "* In instruction (1), `errno` must be initialized before any call to function that modifies it. Unfortunately, the behavior of C standard functions is not consistent regarding their usage of `errno`. For example, most functions defined in `pthread.h` does not modify `errno`. Note that in this small example, the problem of setting `errno` might not appear at first, but in a real software, it is very easy to just forget its initialization. In such a case, the behavior of the process might become completely strange: it might notify about error at some places where the error did not occur.\n",
    "\n",
    "* Instruction (2) is standard practice in C, and we will rely on that for error management: checking the return value of a function.\n",
    "\n",
    "* Instruction (3) uses the `strerror()` POSIX function defined in `string.h` which is not thread safe. It returns a string representing the error message related to the given error code, in our case `errno`.\n",
    "\n",
    "* Instruction (4) is a very simple way to deal with the error: we just display it. However, the message returned by `strerror()` does not hold all the context, in our case for example, the file name. The context should also include the whole call stack. Therefore, the message displayed is not very usefull. Of course, in this simple example, we just can display the file name in the `fprintf()` function, and it will solve the problem. However in the general case, the fact that `strerror()` does not include the context is a problem: you cannot return the value to the caller for example, you have to create a specific structure that includes the context along with the error message (or the code, but not `errno` since it might change afterwards). Error reporting is also very poor: either displays on standard error using one of `perror()` or `error()` or do it yourself with `fprintf()`.\n",
    "\n",
    "* Instruction (5) is also dangerous: `strerror()` does not return an allocated string --- this is the main reason why it cannot include the context by the way --- therefore it must not be freed nor modified.\n",
    "\n",
    "Most modern languages uses [Exception Handling](https://en.wikipedia.org/wiki/Exception_handling) to solve most of those issues: an exception is an object, therefore it can hold a context that helps understanding what the problem is all about. In some languages (e.g. Java), some exceptions cannot be ignored at all, they have to be dealt with by the caller or they must be passed up in the call stack. If C libraries for exception handling [exist](https://github.com/guillermocalvo/exceptions4c/wiki/alternatives) they are of course not standard. \n",
    "\n",
    "Anyway, exception handling has some drawbacks (see [Exception Handling Criticism on Wikipedia](https://en.wikipedia.org/wiki/Exception_handling#Criticism) and [Why should I have written ZeroMQ in C, not C++ (part I)](http://250bpm.com/blog:4), therefore, we prefer to stick with the C return-code tradition.\n",
    "\n",
    "The `bxierr` module has been designed specifically to address those problems. It defines an object-like structure `bxierr_p` that represents the error. Following the C tradition, a function is supposed to return such a `bxierr_p` object in case of error or the special constant `BXIERR_OK` when no problem occurs. \n",
    "\n",
    "In short term, the `bxierr.h` module is:\n",
    "\n",
    "* efficient: determining if an error occurs after a call requires just a check between two pointers: the returned `bxierr_p` object and the constant `BXIERR_OK`; this operation is very fast (as fast as comparing two integers as done in the traditionnal approach);\n",
    "* rich: the returned `bxierr_p` object includes an error code, a message that can include part of the context --- such as the file name in our example --- and the complete call stack;\n",
    "* safer: since a `bxierr_p` object is returned, proper tool such as [Valgrind](valgrind.org) or [Coverity](www.coverity.com) will shout if it is not either destroyed or returned to the caller.\n",
    "\n",
    "This last property prevents errors from being ignored as it is usually done in C (how many times do you really check the code returned by printf()?). However, handling the error after each function call is clearly a pain and makes the code unreadable in the end. Note that one of the feature of exception handling is the ability to factorize the error handling code at one location in the `except/catch` block. The `bxierr.h` module provides various features in this regards:\n",
    "\n",
    "* error chaining: an error can be the cause of another error; \n",
    "* error list: non related errors can be stored in a list;\n",
    "* error set: non related errors can be stored in a set --- that is two errors of the same type (that is   with the same error code) are only stored once; this makes it possible to report only errors once per   kind of errors.\n",
    "\n",
    "\n",
    "The following example illustrates the use of the `bxierr.h` module for high level programming. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {
    "collapsed": false,
    "deletable": true,
    "editable": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "##code## 2\n",
      "##mesg## Problem while opening /a/non/existent/file: No such file or directory\n",
      "##trce## Backtrace of tid 100: 7 function calls \n",
      "##trce## [00] /lib64/libbxibase.so.0(bxierr_backtrace_str+0x195) [0x7fd8adc95f15]\n",
      "##trce## [01] /lib64/libbxibase.so.0(bxierr_new+0x99) [0x7fd8adc96239]\n",
      "##trce## [02] /lib64/libbxibase.so.0(bxierr_vfromidx+0x97) [0x7fd8adc963c7]\n",
      "##trce## [03] /lib64/libbxibase.so.0(bxierr_fromidx+0x94) [0x7fd8adc96504]\n",
      "##trce## [04] /tmp/tmpqovgxgve.out() [0x400828]\n",
      "##trce## [05] /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fd8ad8edb35]\n",
      "##trce## [06] /tmp/tmpqovgxgve.out() [0x400709]\n",
      "##trce## Backtrace end\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": []
    }
   ],
   "source": [
    "#include <stdlib.h>\n",
    "#include <stdio.h>\n",
    "#include <errno.h>\n",
    "#include <bxi/base/err.h>\n",
    "\n",
    "int main(void) {\n",
    "    char * filename = \"/a/non/existent/file\";\n",
    "    errno = 0;                                                   // (1) Don't forget that!\n",
    "    FILE * file = fopen(filename, \"r\");\n",
    "    if (NULL == file) {\n",
    "        bxierr_p err = bxierr_errno(\"Problem while opening %s\",  // (2) Convenient function to create a bxierr_p\n",
    "                                    filename);\n",
    "        bxierr_report(&err, STDERR_FILENO);                      // (3) Convenient function to report an error\n",
    "    } else {\n",
    "        printf(\"Strange: you really have such a file?\\n\");       // This should not happened\n",
    "    }\n",
    "}\n",
    "    "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "deletable": true,
    "editable": true
   },
   "source": [
    "* Instruction (1) is still requires since `fopen()` is called.\n",
    "* Instruction (2) shows a convenient way to create a `bxierr_p` from an `errno` code. There are many other functions for `bxierr_p` creation.\n",
    "* Instruction (3) shows how to report a `bxierr_p`; another more powerfull way will be presented in [Logging System](#Logging System).\n",
    "\n",
    "Notice the output now provides much more information: \n",
    "\n",
    "* the error code;\n",
    "* the message with the file name;\n",
    "* the full call stack.\n",
    "\n",
    "Of course, one might argue that if the file name is required in the output, it just have to be passed to  `fprintf()`, and the result will be somewhat equivalent. In this simple case, where the error is just reported, you will be right --- the call stack will be missing though. However, if the error is not only supposed to be reported, but also to be treated by the caller, the filename must be present in the error itself as a data.\n",
    "\n",
    "The `bxierr.h` module is a real change in C programming, and is one of the most important module for high level programming. To understand that, a more complete example is required: "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {
    "collapsed": false,
    "deletable": true,
    "editable": true,
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "First time seen and reported error: ##code## 2\n",
      "##mesg## An error occured while reading/writing\n",
      "##trce## Backtrace of tid 106: 6 function calls \n",
      "##trce## [00] /lib64/libbxibase.so.0(bxierr_backtrace_str+0x195) [0x7fa8d401ff15]\n",
      "##trce## [01] /lib64/libbxibase.so.0(bxierr_new+0x99) [0x7fa8d4020239]\n",
      "##trce## [02] /tmp/tmpya_j8fyx.out() [0x400d31]\n",
      "##trce## [03] /tmp/tmpya_j8fyx.out() [0x400e49]\n",
      "##trce## [04] /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fa8d3c77b35]\n",
      "##trce## [05] /tmp/tmpya_j8fyx.out() [0x400b59]\n",
      "##trce## Backtrace end\n",
      "First time seen and reported error: ##code## 1\n",
      "##mesg## An error occured while reading/writing\n",
      "##trce## Backtrace of tid 106: 6 function calls \n",
      "##trce## [00] /lib64/libbxibase.so.0(bxierr_backtrace_str+0x195) [0x7fa8d401ff15]\n",
      "##trce## [01] /lib64/libbxibase.so.0(bxierr_new+0x99) [0x7fa8d4020239]\n",
      "##trce## [02] /tmp/tmpya_j8fyx.out() [0x400d31]\n",
      "##trce## [03] /tmp/tmpya_j8fyx.out() [0x400e49]\n",
      "##trce## [04] /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fa8d3c77b35]\n",
      "##trce## [05] /tmp/tmpya_j8fyx.out() [0x400b59]\n",
      "##trce## Backtrace end\n",
      "First time seen and reported error: ##code## 0\n",
      "##mesg## An error occured while reading/writing\n",
      "##trce## Backtrace of tid 106: 6 function calls \n",
      "##trce## [00] /lib64/libbxibase.so.0(bxierr_backtrace_str+0x195) [0x7fa8d401ff15]\n",
      "##trce## [01] /lib64/libbxibase.so.0(bxierr_new+0x99) [0x7fa8d4020239]\n",
      "##trce## [02] /tmp/tmpya_j8fyx.out() [0x400d31]\n",
      "##trce## [03] /tmp/tmpya_j8fyx.out() [0x400e49]\n",
      "##trce## [04] /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fa8d3c77b35]\n",
      "##trce## [05] /tmp/tmpya_j8fyx.out() [0x400b59]\n",
      "##trce## Backtrace end\n",
      "\n",
      "--- End of first time seen error reporting ---\n",
      "##code## 888\n",
      "##mesg## Maximal number of distinct errors reached: 3/7\n",
      "##trce## Backtrace of tid 106: 6 function calls \n",
      "##trce## [00] /lib64/libbxibase.so.0(bxierr_backtrace_str+0x195) [0x7fa8d401ff15]\n",
      "##trce## [01] /lib64/libbxibase.so.0(bxierr_new+0x99) [0x7fa8d4020239]\n",
      "##trce## [02] /tmp/tmpya_j8fyx.out() [0x400df8]\n",
      "##trce## [03] /tmp/tmpya_j8fyx.out() [0x400e49]\n",
      "##trce## [04] /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fa8d3c77b35]\n",
      "##trce## [05] /tmp/tmpya_j8fyx.out() [0x400b59]\n",
      "##trce## Backtrace end\n",
      "\n",
      "... caused by:\n",
      "\n",
      "##code## 999\n",
      "##mesg## At least one error occurs\n",
      "##trce## Backtrace of tid 106: 6 function calls \n",
      "##trce## [00] /lib64/libbxibase.so.0(bxierr_backtrace_str+0x195) [0x7fa8d401ff15]\n",
      "##trce## [01] /lib64/libbxibase.so.0(bxierr_new+0x99) [0x7fa8d4020239]\n",
      "##trce## [02] /tmp/tmpya_j8fyx.out() [0x400cca]\n",
      "##trce## [03] /tmp/tmpya_j8fyx.out() [0x400e28]\n",
      "##trce## [04] /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fa8d3c77b35]\n",
      "##trce## [05] /tmp/tmpya_j8fyx.out() [0x400b59]\n",
      "##trce## Backtrace end\n",
      "\n",
      "Error n°0\n",
      "\n",
      "##code## 5\n",
      "##mesg## Error returned from thread 0\n",
      "##trce## Backtrace of tid 106: 6 function calls \n",
      "##trce## [00] /lib64/libbxibase.so.0(bxierr_backtrace_str+0x195) [0x7fa8d401ff15]\n",
      "##trce## [01] /lib64/libbxibase.so.0(bxierr_new+0x99) [0x7fa8d4020239]\n",
      "##trce## [02] /tmp/tmpya_j8fyx.out() [0x400c6f]\n",
      "##trce## [03] /tmp/tmpya_j8fyx.out() [0x400e28]\n",
      "##trce## [04] /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fa8d3c77b35]\n",
      "##trce## [05] /tmp/tmpya_j8fyx.out() [0x400b59]\n",
      "##trce## Backtrace end\n",
      "\n",
      "Error n°1\n",
      "\n",
      "##code## 5\n",
      "##mesg## Error returned from thread 1\n",
      "##trce## Backtrace of tid 106: 6 function calls \n",
      "##trce## [00] /lib64/libbxibase.so.0(bxierr_backtrace_str+0x195) [0x7fa8d401ff15]\n",
      "##trce## [01] /lib64/libbxibase.so.0(bxierr_new+0x99) [0x7fa8d4020239]\n",
      "##trce## [02] /tmp/tmpya_j8fyx.out() [0x400c6f]\n",
      "##trce## [03] /tmp/tmpya_j8fyx.out() [0x400e28]\n",
      "##trce## [04] /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fa8d3c77b35]\n",
      "##trce## [05] /tmp/tmpya_j8fyx.out() [0x400b59]\n",
      "##trce## Backtrace end\n",
      "\n",
      "Error n°2\n",
      "\n",
      "##code## 5\n",
      "##mesg## Error returned from thread 2\n",
      "##trce## Backtrace of tid 106: 6 function calls \n",
      "##trce## [00] /lib64/libbxibase.so.0(bxierr_backtrace_str+0x195) [0x7fa8d401ff15]\n",
      "##trce## [01] /lib64/libbxibase.so.0(bxierr_new+0x99) [0x7fa8d4020239]\n",
      "##trce## [02] /tmp/tmpya_j8fyx.out() [0x400c6f]\n",
      "##trce## [03] /tmp/tmpya_j8fyx.out() [0x400e28]\n",
      "##trce## [04] /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fa8d3c77b35]\n",
      "##trce## [05] /tmp/tmpya_j8fyx.out() [0x400b59]\n",
      "##trce## Backtrace end\n",
      "\n",
      "Error n°3\n",
      "\n",
      "##code## 5\n",
      "##mesg## Error returned from thread 3\n",
      "##trce## Backtrace of tid 106: 6 function calls \n",
      "##trce## [00] /lib64/libbxibase.so.0(bxierr_backtrace_str+0x195) [0x7fa8d401ff15]\n",
      "##trce## [01] /lib64/libbxibase.so.0(bxierr_new+0x99) [0x7fa8d4020239]\n",
      "##trce## [02] /tmp/tmpya_j8fyx.out() [0x400c6f]\n",
      "##trce## [03] /tmp/tmpya_j8fyx.out() [0x400e28]\n",
      "##trce## [04] /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fa8d3c77b35]\n",
      "##trce## [05] /tmp/tmpya_j8fyx.out() [0x400b59]\n",
      "##trce## Backtrace end\n",
      "\n",
      "Error n°4\n",
      "\n",
      "##code## 5\n",
      "##mesg## Error returned from thread 4\n",
      "##trce## Backtrace of tid 106: 6 function calls \n",
      "##trce## [00] /lib64/libbxibase.so.0(bxierr_backtrace_str+0x195) [0x7fa8d401ff15]\n",
      "##trce## [01] /lib64/libbxibase.so.0(bxierr_new+0x99) [0x7fa8d4020239]\n",
      "##trce## [02] /tmp/tmpya_j8fyx.out() [0x400c6f]\n",
      "##trce## [03] /tmp/tmpya_j8fyx.out() [0x400e28]\n",
      "##trce## [04] /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fa8d3c77b35]\n",
      "##trce## [05] /tmp/tmpya_j8fyx.out() [0x400b59]\n",
      "##trce## Backtrace end\n",
      "\n",
      "Error n°0\n",
      "\n",
      "##code## 2\n",
      "##mesg## An error occured while reading/writing\n",
      "##trce## Backtrace of tid 106: 6 function calls \n",
      "##trce## [00] /lib64/libbxibase.so.0(bxierr_backtrace_str+0x195) [0x7fa8d401ff15]\n",
      "##trce## [01] /lib64/libbxibase.so.0(bxierr_new+0x99) [0x7fa8d4020239]\n",
      "##trce## [02] /tmp/tmpya_j8fyx.out() [0x400d31]\n",
      "##trce## [03] /tmp/tmpya_j8fyx.out() [0x400e49]\n",
      "##trce## [04] /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fa8d3c77b35]\n",
      "##trce## [05] /tmp/tmpya_j8fyx.out() [0x400b59]\n",
      "##trce## Backtrace end\n",
      "\n",
      "Error n°1\n",
      "\n",
      "##code## 1\n",
      "##mesg## An error occured while reading/writing\n",
      "##trce## Backtrace of tid 106: 6 function calls \n",
      "##trce## [00] /lib64/libbxibase.so.0(bxierr_backtrace_str+0x195) [0x7fa8d401ff15]\n",
      "##trce## [01] /lib64/libbxibase.so.0(bxierr_new+0x99) [0x7fa8d4020239]\n",
      "##trce## [02] /tmp/tmpya_j8fyx.out() [0x400d31]\n",
      "##trce## [03] /tmp/tmpya_j8fyx.out() [0x400e49]\n",
      "##trce## [04] /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fa8d3c77b35]\n",
      "##trce## [05] /tmp/tmpya_j8fyx.out() [0x400b59]\n",
      "##trce## Backtrace end\n",
      "\n",
      "Error n°2\n",
      "\n",
      "##code## 0\n",
      "##mesg## An error occured while reading/writing\n",
      "##trce## Backtrace of tid 106: 6 function calls \n",
      "##trce## [00] /lib64/libbxibase.so.0(bxierr_backtrace_str+0x195) [0x7fa8d401ff15]\n",
      "##trce## [01] /lib64/libbxibase.so.0(bxierr_new+0x99) [0x7fa8d4020239]\n",
      "##trce## [02] /tmp/tmpya_j8fyx.out() [0x400d31]\n",
      "##trce## [03] /tmp/tmpya_j8fyx.out() [0x400e49]\n",
      "##trce## [04] /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fa8d3c77b35]\n",
      "##trce## [05] /tmp/tmpya_j8fyx.out() [0x400b59]\n",
      "##trce## Backtrace end\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": []
    }
   ],
   "source": [
    "#include <stdlib.h>\n",
    "#include <time.h>\n",
    "#include <bxi/base/err.h>\n",
    "\n",
    "bxierr_p f() {\n",
    "    // This function actually generates many independant errors, we store them in a list\n",
    "    bxierr_list_p err_list = bxierr_list_new();\n",
    "    for (size_t i = 0; i < 5; i++) {\n",
    "        // For example, some files are opened\n",
    "        // open(...)\n",
    "        bxierr_p err = bxierr_simple(5, \"Error returned from thread %d\", i); // An error type is given by an integer code\n",
    "        bxierr_list_append(err_list, err);\n",
    "    }\n",
    "    return (0 == err_list->errors_nb) ? BXIERR_OK : bxierr_from_list(999, err_list, \"At least one error occurs\");  \n",
    "}\n",
    "\n",
    "bxierr_p g() {\n",
    "    // This function might generate many errors in a loop, instead of storing each one of them,\n",
    "    // we only store each distinct ones, limiting the number of reports.\n",
    "    bxierr_set_p err_set = bxierr_set_new();\n",
    "    while (3 > err_set->distinct_err.errors_nb) {\n",
    "        // This loop is for example, accessing a file on a regular basis but must never crash even on error.\n",
    "        // However error reporting is important. We report an error only the first time it is seen\n",
    "        // read(...) or write(...)\n",
    "        long int err_type = rand() % 4; // Let's suppose only 4 types of errors \n",
    "        bxierr_p err = bxierr_simple(err_type, \"An error occured while reading/writing\");\n",
    "        if (bxierr_set_add(err_set, &err)) {\n",
    "            // First time such an error is seen, we might report it \n",
    "            char * err_str = bxierr_str(err);\n",
    "            fprintf(stderr, \"First time seen and reported error: %s\", err_str);\n",
    "            BXIFREE(err_str);\n",
    "        } // This error has already been seen, so we don't procude any report, note that it has already been destroyed\n",
    "    }\n",
    "    fprintf(stderr, \"\\n--- End of first time seen error reporting ---\\n\");\n",
    "    \n",
    "    return bxierr_from_set(888, err_set, \"Maximal number of distinct errors reached: %zu/%zu\", \n",
    "                                err_set->distinct_err.errors_nb, err_set->total_seen_nb);\n",
    "}\n",
    "\n",
    "int main() {\n",
    "    bxierr_p err = BXIERR_OK, err2;\n",
    "    \n",
    "    srand(time(NULL));\n",
    "    err2 = f();\n",
    "    BXIERR_CHAIN(err, err2); // We don't want to deal with the error here\n",
    "    \n",
    "    err2 = g();\n",
    "    BXIERR_CHAIN(err, err2); // Here, we chain both error, meaning that errors from f() might cause g() \n",
    "                             // to returned errors too\n",
    "    \n",
    "    bxierr_report(&err, STDERR_FILENO);\n",
    "}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "deletable": true,
    "editable": true
   },
   "source": [
    "The `main()` illustrates the *error chaining pattern*: errors from function `f()` and  `g()` are not ignored; the error-handling code --- in this simple case, producing a report thanks to `bxierr_report()` --- is at the end of the program. If `f()` produces an error --- what will always happen in this simple case --- it will be the cause of the error produced by `g()` if any. Basically, an error can be dealt with in three different ways:\n",
    "\n",
    "* you report it directly using bxierr_report or even better, using `BXILOG_REPORT` as we will see in next section, or with `fprintf()` or whatever reporting system (note: the error is normally destroyed after this step);\n",
    "* you pass it to the caller using a simple `return` statement;\n",
    "* you try to continue anyway, in this case, you chain using `BXIERR_CHAIN()`.\n",
    "\n",
    "Function `f()` uses the `bxierr_list_p` structure to store the different errors and turn them into a normal `bxierr_p` object.\n",
    "\n",
    "Function `g()` uses the `bxierr_set_p` structure to only store distinct errors: the idea is to prevent a software from producing many identical reports such as \"Can't write to file ...: disk full\". Such a report should only be reported once using this simple but powerful mechanism.\n",
    "\n",
    "The `bxierr.h` module provides very limited reporting facility: it is therefore only useful when nothing else is available. In particular, the `bxilog.h` module is much preferable for reporting as we will see in [Logging System](Logging System.ipynb)."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "C",
   "language": "c",
   "name": "c_spec"
  },
  "language_info": {
   "file_extension": "c",
   "mimetype": "text/plain",
   "name": "c"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
